name: Azure Dev

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Install local certs
      shell: bash
      run: |
        dotnet dev-certs https --trust

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build -c Release --no-restore --no-incremental

    - name: Install playwright
      shell: pwsh
      run: |
        $playwright = Get-ChildItem -File Microsoft.Playwright.dll -Path . -Recurse
        $installer = "$($playwright[0].Directory.FullName)/playwright.ps1"
        & "$installer" install

    - name: Run app in background
      shell: bash
      run: |
        dotnet user-secrets --project ./src/OpenChat.PlaygroundApp \
            set GitHubModels:Token "temporary-dummy-token"

        dotnet run --project ./src/OpenChat.PlaygroundApp &

        sleep 30

    - name: Run tests
      shell: bash
      run: |
        dotnet test . -c Release --no-build --logger "trx" --collect:"XPlat Code Coverage" --filter "Category!=LLMRequired"
